[build]
target = "thumbv4t-none-eabi"

[unstable]
build-std = ["core", "alloc"]

[target.thumbv4t-none-eabi]
rustflags = ["-Clink-arg=-Tlinker_scripts/mono_boot.ld"]
runner = "/Applications/mGBA.app/Contents/MacOS/mGBA"

[alias]
gba-build = "build --target thumbv4t-none-eabi --release"
gba-run = "run --target thumbv4t-none-eabi --release"
gba-run-dbg = "run --target thumbv4t-none-eabi"
